# 注册到eureka-server上
eureka:
  instance:
    # 主机名称
    hostname: ${spring.cloud.client.ipAddress}
    # 自定义实例ID
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    # 显示IP地址
    prefer-ip-address: true
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 过期剔除时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10
  client:
    # 是否将eureka自身作为应用注册到eureka注册中心
    register-with-eureka: true
    # 客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: true
    # 设置拉取服务注册信息时间（缺省为60s）
    registry-fetch-interval-seconds: 30
    # Eureka服务
    serviceUrl:
      #服务注册中心地址
      defaultZone: http://127.0.0.1:8000/eureka/


#sprig:
#  mail:
#    default-encoding: utf-8
#    protocol: smtp
#    host: smtp.163.com
#    port: 465
#    username: tzz_funet@163.com
#    password: QQ2018com
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#      smtp:
#        auth: true
#        starttls:
#          enable: true
#          required: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

feign:
  httpclient:
    enabled: true

upload:
  rootpath: /home/vpclub/www-upload
  serverurl: https://tzz.vpclub.com/upload

ueditor:
  config: config.json
  unified: true
  upload-path: /home/vpclub/www-upload
  url-prefix: https://tzz.vpclub.com/upload

wx:
  payCallback: https://tzz.vpclub.com/api/callBack/weixinPay
  refundCallback: https://tzz.vpclub.com/api/callBack/refundOrder

bw:
  path: https://tzz.vpclub.com/api